version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql:rw,z
    expose:
      - 5432
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTERNAL_PORT=15432
      - POSTGRES_DB=df-bridge

  bridge:
    container_name: bridge
    build: ./
    image: dfinity-bridge
    restart: always
    links:
      - postgres
      - init-service
    command: ['node', 'dist/apps/bridge/main.js']
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - '3000:3000'
    expose:
      - 3000

  polygon-listener:
    container_name: polygon-listener
    build: ./
    image: dfinity-bridge
    restart: always
    links:
      - postgres
      - init-service
    command: [ 'node', 'dist/apps/polygon-listener/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - '3001:3001'
    expose:
      - 3001

  init-service:
    container_name: init-service2
    build: ./
    image: dfinity-bridge
    links:
      - postgres
    command: ['node', 'dist/apps/init-service/main.js']
    environment:
      - NODE_ENV=${NODE_ENV:-development}
