---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22
    ansible_connection: ssh
    docker_compose_version: v2.2.3

project:
  hosts:
    develop:
      ansible_host: 3.133.141.128
      ansible_user: ec2-user